### ISSUE TITLE
[BUG] Portfolios number and avg nb of assets per portfolio" are wrong in the Population.summary() report.

### ISSUE THREAD

**Issue by CarloNicolini** [skfolio/skfolio#19]
**Describe the bug**
The last two lines "Portfolios number" and "Avg nb of assets per portfolio" report the wrong dimension in the resulting dataframe of the `Population.summary()` when objects resulting from a `cross_val_predict` are used to initialize the `Population` object.

**To Reproduce**
```python
from skfolio.model_selection import WalkForward

from skfolio import RiskMeasure, RatioMeasure
from skfolio.optimization import MeanRisk, HierarchicalRiskParity, EqualWeighted
from skfolio.population import Population

from skfolio.model_selection import cross_val_predict

estimators = {
    "minvol": MeanRisk(risk_measure=RiskMeasure.VARIANCE, transaction_costs=0),
    "mad": MeanRisk(
        risk_measure=RiskMeasure.MEAN_ABSOLUTE_DEVIATION, transaction_costs=0
    ),
    "ew": EqualWeighted(),
    "hrp": HierarchicalRiskParity(risk_measure=RiskMeasure.VARIANCE,transaction_costs=0),
}

cv_preds = {}
for name, estimator in estimators.items():
    cv_preds[name] = cross_val_predict(
        estimator=estimator,
        X=train_returns,
        cv=WalkForward(test_size=252, train_size=9 * 252, expend_train=False),
        n_jobs=1,
    )

cv_pop = Population(list(cv_preds.values()))
cv_pop.summary()
```

**Expected behavior**
The "Avg nb of assets per portfolio" could be the average of the effective number of assets (like described in PR #17).
The portfolios number is not clear to me though.

**Versions**
0.0.9

**Comment by HugoDelatte** [comment]
The error of the nb of assets comes from [here](https://github.com/skfolio/skfolio/blob/c2fdd820f47ba62cf79a9581241ebb682180cc89/src/skfolio/portfolio/_multi_period_portfolio.py#L573) and [here](https://github.com/skfolio/skfolio/blob/c2fdd820f47ba62cf79a9581241ebb682180cc89/src/skfolio/portfolio/_multi_period_portfolio.py#L574C9-L574C67)

Both coming from how `__len__` has been defined. 

Here is a summary:

- `Portfolio`: defined from a vector of asset weights and a matrix of price returns --> currently `__len__` returns the number of observation : `len(self.observations)`
- `MultiPeriodPortfolio`: defined from a list of `Portfolio` and inherits the same methods --> currently `__len__`  returns the same as `Portfolio`: `len(self.observations)` where `observations` are the concatenation of each `Portfolio` observations. 
- `Population`:  defined from a list of `Portfolio` or `MultiPeriodPortfolio` and inherits from `list` --> `__len__` returns the number of portfolios.

I'm going to correct the two issues in the `MultiPeriodPortfolio` summary function but we should also discuss the `__len__` method. Calling `len` on a  `MultiPeriodPortfolio` should maybe return the number of portfolios instead of the number of observations, but then it would differ from calling `len` on `Portfolio` which we don't want. So we would also need to delete the `len` method of `Portfolio`.

What are your thoughts?

**Comment by CarloNicolini** [comment]
The `__len__` method is unintuitive to me as it has no direct relation to anything which a portfolio manager knows. It is also not very *sklear-friendly* imho.
I believe at this point having a clearer naming could be more helpful, and giving up `__len__` would help.
As in linux, a single function does the same thing.

**Comment by HugoDelatte** [comment]
I agree, let's remove it

**Comment by HugoDelatte** [comment]
Should close automatically as soons as [this PR](https://github.com/skfolio/skfolio/pull/21) is merged
