### ISSUE TITLE
prices_to_returns cuts off dataframe to last asset launch [BUG]

### ISSUE THREAD

**Issue by 8W9aG** [skfolio/skfolio#55]
**Describe the bug**

`prices_to_returns` promises to take a dataframe of prices and convert them to returns. In the event I have a dataframe with returns with different starting times (such as `VTI` and `BITI`) this function will cut rows to the start of `BITI`.

**To Reproduce**

```python
from skfolio.preprocessing import prices_to_returns
import yfinance as yf
import pandas as pd

STOCKS = ["VTI", "BITI"]
return_dfs = []
for ticker in STOCKS:
  ticker_yahoo = yf.Ticker(ticker)
  df = ticker_yahoo.history(period="1d", start="2010-01-01")
  df.index = df.index.date
  return_dfs.append(df[["Close"]].rename(columns={"Close": ticker}))
return_df = pd.concat(return_dfs, axis=1).sort_index().fillna(0.0)

prices_to_returns(return_df)
```

**Expected behavior**

Returns for `BITI` before `2022-06-21` are 0.0. Instead it cuts off the dataframe.

**Additional context**

This occurs due to the [dropna](https://github.com/skfolio/skfolio/blob/67a2a18288fcecd5f911d67402e6839b0332fa5a/src/skfolio/preprocessing/_returns.py#L107). I believe this should use `fillna` with 0.0 after the `pct_change` call to mark the previous periods are 0.0 for returns. I would be more than happy to make this change just want to be sure this is considered the right move by the maintainers.

**Versions**

`0.2.1`

**Comment by HugoDelatte** [comment]
The `prices_to_returns` function currently forward fill missing values (NaN) and drop all dates that have missing values placed at the start. The reason we don't apply a backfill is to avoid data leakage. However, we need to have an option to keep these NaNs at the beginning because in some cases we can use a Pre-Selection Transformer that drops assets that have not started yet while keeping the older ones. 

In your example, you are replacing NaNs with 0 but on the prices, therefore the return computation will return NaNs, one Inf, then the correct returns. The NaNs will indeed be dropped by the dropna.

**Comment by HugoDelatte** [comment]
The `prices_to_returns` function currently forward fill missing values (NaN) and drop all dates that have missing values placed at the start. The reason we don't apply a backfill is to avoid data leakage. However, we need to have an option to keep these NaNs at the beginning because in some cases we can use a Pre-Selection Transformer that drops assets that have not started yet while keeping the older ones.

In your example, you are replacing NaNs with 0 but on the prices, therefore the return computation will return NaNs, one Inf, then the correct returns. The NaNs will indeed be dropped by the dropna.

The proper way would be to implement the improvement I just described, then if you need you can replace the returns NaN with 0

**Comment by HugoDelatte** [comment]
I think we should also raise an explicit Error when prices are 0 or neg

**Comment by 8W9aG** [comment]
I'm not quite sure I follow the improvement you are describing, can you give me some colour around what this would look like mechanically?

**Comment by HugoDelatte** [comment]
Let's assume you have two assets with the below **prices** time series:

`p0, p1, p2, p3, nan, p5, p6`
`nan, nan, nan, p3, p4, nan, p6`

The `prices_to_returns` function with it's default param `nan_threshold=1.0` will first forward fill the prices:
`p0, p1, p2, p3, p3, p5, p6`
`nan, nan, nan, p3, p4, p4, p6`

Then compute the returns:
`nan, r1, r2, r3, r4, r5, r6`
`nan, nan, nan, nan, r4, r5, r6`

Then remove all NaNs:
`r4, r5, r6`
`r4, r5, r6`

I'm proposing to have another parameter to keep rows with partial NaNs for this last step. So we would get:
`r1, r2, r3, r4, r5, r6`
`nan, nan, nan, r4, r5, r6`
