### ISSUE TITLE
MultiPeriodPortfolio Contribution

### ISSUE THREAD

**Issue by firmai** [skfolio/skfolio#72]
We currently have MultiPeriodPortfolio.`composition` which is helpful, it would be great if we could do the same for MultiPeriodPortfolio.`contribution`, which would allow us again to have something similar to composition over the different test sets, 
![image](https://github.com/user-attachments/assets/84dcc275-f6bb-4758-a2df-59fe141b7b99)

Or as recommended in https://github.com/skfolio/skfolio/issues/69#issuecomment-2245173419 a date type Contribution that rolls forward. 

![image](https://github.com/user-attachments/assets/07591938-06f6-4e54-bbed-729b0a914adb)

**Comment by HugoDelatte** [comment]
Yes I agree, let's implement it. We can follow the same logic as `composition`:
* make it an `abstractmethod` in `BasePortfolio`
* move `plot_contribution` from `Portfolio` to `BasePortfolio`
* implement `contribution` in `MultiPeriodPortfolio` following `composition` logic

I haven't tested it so it may not be the best approach so let's see.
Let me know if you wish to do this PR, otherwise I can do it.

**Comment by HugoDelatte** [comment]
Implementation done in dev branch here:

For MultiPeriodPortfolio:
https://github.com/skfolio/skfolio/blob/128f619960494f827fb2205e1a9d5cca383092d8/src/skfolio/portfolio/_multi_period_portfolio.py#L559


And for Population:
https://github.com/skfolio/skfolio/blob/128f619960494f827fb2205e1a9d5cca383092d8/src/skfolio/population/_population.py#L407

And Plot:
https://github.com/skfolio/skfolio/blob/128f619960494f827fb2205e1a9d5cca383092d8/src/skfolio/population/_population.py#L648
