### ISSUE TITLE
SolverError: Solver 'CLARABEL' failed

### ISSUE THREAD

**Issue by jmlocatelli** [skfolio/skfolio#81]
I frequently receive this message:

SolverError: Solver 'CLARABEL' failed for . Try another solver, or solve with solver_params=dict(verbose=True) for more information

What can I change to work around? 

jm

**Comment by HugoDelatte** [comment]
That error means that the underlying default convex solver named CLARABEL could not find a solution.

Most of the time, this indicates that you are trying to solve an infeasible problem. The solution is to loosen some of your constraints.

In rare cases, it occurs when the solver didn't converge properly while the problem was feasible. In such cases, you can adjust the solver settings and scaling factors. However, that's rare (if you look at our unit tests, the solver systematically found the solution in over 3,000 tests on very diverse problems and datasets).

If you send me the problem you are trying to solve I could tell you what's happening.
